
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sddf2012/configserver
          username: sddf2012
          password: sh54410
  application:
    name: configserver

server:
  port: 7000