server:
  port: 7001

spring:
  application:
    name: registryserver
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: configserver
#      profile: dev
#      label: master
#      username: config
#      password: config
#      fail-fast: true
  # 数据库配置
  datasource:
    # ---------------基本链接信息---------------------------
    url: jdbc:mysql://localhost:3306/ms_base?serverTimezone=UTC
    username: root
    password: root
    # -----------------初始化大小，最小，最大----------------------------
    initialSize: 1
    minIdle: 1
    maxActive: 32
    #是否在自动回收超时连接的时候打印连接的超时错误
    logAbandoned: true
    #是否自动回收超时连接
    removeAbandoned: true
    #超时时间(以秒数为单位)
    removeAbandonedTimeout: 60
    # 配置获取连接等待超时的时间(以毫秒为单位)
    maxWait: 1000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 6000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT 'OK'
    testWhileIdle: true
    testOnBorrow: false
    test-on-Return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000
    # 合并多个DruidDataSource的监控数据
    # useGlobalDataSourceStat: true

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: false
    register-with-eureka: false
  server:
    enable-self-preservation: true


logging:
  level:
    root: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

test:
  a: 123